version: "3.9"

services:
  db:
    image: postgres:15
    container_name: h2ready_db
    environment:
      POSTGRES_USER: h2ready
      POSTGRES_PASSWORD: h2ready_password
      POSTGRES_DB: h2ready
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: h2ready_backend
    environment:
      DATABASE_URL: postgresql+psycopg2://h2ready:h2ready_password@db:5432/h2ready
      APP_ENV: dev
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: h2ready_frontend
    environment:
      API_BASE_URL: http://backend:8000
    ports:
      - "8501:8501"
    depends_on:
      - backend

volumes:
  db_data:
